instrumentation:
    root: ./src/js
    extensions:
        - .js
    default-excludes: true
    excludes: [
      './src/js/main.js',
      './src/js/routes.js',
      './src/js/components/ArtefactCanvas.vue',
      './src/js/components/ArtefactCanvas.vue',
      './src/js/components/SingleImage.vue'
    ]