language: node_js
node_js:
  - 8
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "npm run test_travis"